Add example usage of TerraformTaskV3 and fix typos
microsoft/azure-pipelines-terraform pull request #91
Opened 2022-10-13 21:20 UTC by hikilaka

I have added a few example usages of the TerraformTaskV3 to the README for this task. Additionally, I have corrected a few typos in the same README.

2022-10-13 21:23 UTC, hikilaka commented
I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

2022-10-14 13:07 UTC, mericstam commented
looks good! I just want to verify one thing regarding service connections before I review and approve it

2022-10-17 17:09 UTC, mericstam commented on Tasks/TerraformTask/TerraformTaskV3/README.md
> +    environmentServiceNameAzureRM: 'your-service-connection'
sam here.
```suggestion
    environmentServiceNameAzureRM: 'your-environment-service-connection'
```

2022-10-17 17:11 UTC, mericstam requested changes
LGTM but consider changes

2022-10-17 17:11 UTC, mericstam commented on Tasks/TerraformTask/TerraformTaskV3/README.md
> +    environmentServiceNameAzureRM: 'your-service-connection'
And here as well
```suggestion
        environmentServiceNameAzureRM: 'your-environment-service-connection'
```

2022-10-27 09:05 UTC, mericstam approved these changes

2022-10-27 09:09 UTC, merged